### ISSUE TITLE
Design Website Home Page

### ISSUE THREAD

**Issue by toliujiayi** [hicodingclub/clubweb#1]
Design the website's home page

Components to Include:
- Introduction of HiCodingClub
- Pictures
- A place that links to the volunteer home page
- A place that links to the customer (people who need websites) page
- Contact Information
- Other things that are useful

For additional clarity please check the readme.md document.

This task includes many subtasks. This issue will complete after all subtasks are done.

**Comment by Elizabeth-lizard** [comment]
nice websites that I can leech off of:
https://codeclub.org/en/
https://ourcodingclub.github.io/
https://www.sunrisemovement.org/

**Comment by toliujiayi** [comment]
All subtasks finished. Done :)
