### ISSUE TITLE
HiCodingClub Organization

### ISSUE THREAD

**Issue by toliujiayi** [hicodingclub/clubweb#12]
Organize HiCodingClub board. Create board positions, duties, rules, etc.

**Comment by ericsheng495** [comment]
[https://docs.google.com/document/d/1d2mw6UBXC7cz92lwius6sr0wW5gYzR1smCs_QV-gGnI/edit?usp=sharing](url)

**Comment by toliujiayi** [comment]
update specific roles for the positions
