### ISSUE TITLE
Homepage design -- study other club homepages

### ISSUE THREAD

**Issue by toliujiayi** [hicodingclub/clubweb#2]
This is the subtask of #1 

Find club, computer science, and volunteer related websites and study their homepage design about

- layout
- color theme
- font
- content
- picture
- user interaction
- etc.

**Expected Output:**
- A document summarizing what you learned, features you liked best, and why

**Comment by elizabeth-li-shuxuan** [comment]
nice websites that I can leech off of:
https://codeclub.org/en/
https://ourcodingclub.github.io/
https://www.sunrisemovement.org/

**Comment by toliujiayi** [comment]
Any specific things you learned that is helpful? Please write them down in a document. (If you are already doing this please ignore me)

**Comment by elizabeth-li-shuxuan** [comment]
https://docs.google.com/document/d/1yV4-ED1CEM6mtgSDYS7YvMVJn7fQ_e3k1VWm3qCjdp8/edit?usp=sharing

feel free to comment your suggestions

**Comment by toliujiayi** [comment]
very nicely done!!! great start!!!
