### ISSUE TITLE
New Member Training Slide

### ISSUE THREAD

**Issue by toliujiayi** [hicodingclub/clubweb#23]
Create a 1-3 page training slide introducing and going over your team's job.

**Comment by ericsheng495** [comment]
https://docs.google.com/presentation/d/1gTWnqJ18DiGI561dEgJhF_ull8zFLlD4qJKnMvxKsnA/edit?usp=sharing

**Comment by andrewnpaul** [comment]
https://docs.google.com/presentation/d/16I_yqpuPqysf3jSWkflht28_ycew5DPKvYScPGkk7Lg

Will add more soon

**Comment by andrewnpaul** [comment]
https://docs.google.com/presentation/d/16I_yqpuPqysf3jSWkflht28_ycew5DPKvYScPGkk7Lg

Will add more soon
