### ISSUE TITLE
Info on the member and customer page

### ISSUE THREAD

**Issue by toliujiayi** [hicodingclub/clubweb#24]
write about what information to put on the member and customer page. Don't need to code up anything.

**Comment by andrewnpaul** [comment]
**Become a member**

Interested in joining the Hi-Coding Club? Please complete this form to apply: link to google form. If you have questions about our club, email hcclub@mail.com

Why join Hi Coding Club? There are many opportunies for our members

**Customer**

Would you like Hi-Coding Club to help with a project? We'd be interested. Please let us know at hcclub@mail.com.

**Comment by toliujiayi** [comment]
Member: pictures, benefits (opportunities), procedure/what to expect after becoming a member

Customer: projects we did before, Why us section
