### ISSUE TITLE
Info on the about us page

### ISSUE THREAD

**Issue by toliujiayi** [hicodingclub/clubweb#25]
Write about what information to put on the about us page (team leaders, how our club basically functions, ...)

**Comment by ericsheng495** [comment]
### **HiCoding Club Overview** 

HiCoding club is a nonprofit organization that seeks to help out local small business companies in creating user interactive websites to advertise to a boarder range of markets. Currently, club members will meet every week via Skype to discuss future plans and tasks for the club. As the club grows bigger, general meetings will be separated into team meetings. 

**Teams** 
The HiCoding club is primarliy composed of 4 task categories: UI Design, Coding, Outreach and Quality Assurance. Each individual task group has one leader who is responsible for holding team training/meeting sessions, providing task feedbacks and making sure deadlines are met. 

**Board**
The HiCoding club board is composed of three leadership positions(President, Vice President, and Secretary) and regular board members. Regular Board members are team leaders and club members with more web design experiences. The club President and vice president are responsible for holding club meetings and communicating with team leaders. The club secretary is also responsible for taking notes from board meetings and provide necessary feedbacks with the teams.

**Comment by toliujiayi** [comment]
History and Projects that we did before
