### ISSUE TITLE
Homepage Design -- Learn How to Use Figma

### ISSUE THREAD

**Issue by toliujiayi** [hicodingclub/clubweb#3]
This is the subtask of #1 

We decided to use [Figma](https://www.figma.com/) as our UI design tool

Study online courses about UI design and how to use Figma

**Expected Output:** 
- Show us something you learned or things you designed as practice.

**Comment by elizabeth-li-shuxuan** [comment]
Keyboard tricks in Figma that everyone already knows:
Ctrl G: group items
hold alt: basically copy and paste an item

Layout grid is a helpful thing

This is a great video for intro to Figma: https://www.youtube.com/watch?v=FK4YusHIIj0

**Comment by elizabeth-li-shuxuan** [comment]
There is a file called "I dont know whats going on"
I use this for figuring out things when I don't know what's going on
If anyone goes on Figma and is clueless, feel free to experiment with this file :)
