### ISSUE TITLE
New Member Recruiting Materials and Procedures

### ISSUE THREAD

**Issue by toliujiayi** [hicodingclub/clubweb#6]
We need more members to join our HiCodingClub.

Please come up with ways and materials to spread our club's information as well as defining the procedures for a new member to join our club.

**Comment by andrewnpaul** [comment]
Sharing club info: Tell your friends at school. Post on Instagram or other social media. Post flyers of our club in your local library if allowed. Contact your high school’s programming club and ask them if we can advertise our club. Make sure to make our club sound interesting and fun.
