### ISSUE TITLE
New Member Recruiting -- Procedure for New Member to Join

### ISSUE THREAD

**Issue by toliujiayi** [hicodingclub/clubweb#8]
Subtask of #6 

We simply cannot recruit everyone.

Come up with a procedure that verifies the eligibility of an applicant
Come up with what to do to rejected applicants.

**Expected Output:**
- In a document write down the procedure and related materials (for example, if there are questionnaires, then write down the questions)

**Comment by andrewnpaul** [comment]
https://docs.google.com/document/d/1VMynG4JnHQXVkuvUdwDqyi2ymqE0_9jnp_wVkDRiCJM/edit

**Comment by andrewnpaul** [comment]
https://docs.google.com/document/d/1VMynG4JnHQXVkuvUdwDqyi2ymqE0_9jnp_wVkDRiCJM/edit
