### ISSUE TITLE
Member Communication

### ISSUE THREAD

**Issue by toliujiayi** [hicodingclub/clubweb#9]
As the number of members grows, we need a new way for people to communicate and collaborate. Come up with ways people can meet up, communicate, and collaborate when more and more people join HiCodingClub

**Expected Output:**

- In a document, in the form of a proposal, write down and explain the ways members can communicate and collaborate. 

Board members will be voting on the proposal and if the board agrees there will be a test run on the proposed mean.

**Comment by ericsheng495** [comment]
[https://docs.google.com/document/d/1XZbeZ_yKSJ2Y6IC_HppKjPUDs7PMUKAPnnyaUuXbmpE/edit?usp=sharing](url)
